apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2018-05-07T09:08:41Z","generation":2,"labels":{"env":"prod","run":"yizhangyichi-api","version":"4bc2daf0f595725d8b20"},"name":"yizhangyichi-api","namespace":"default","resourceVersion":"238929","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/yizhangyichi-api","uid":"3c696ef9-51d6-11e8-9a8b-42010af0022e"},"spec":{"replicas":1,"selector":{"matchLabels":{"env":"prod","run":"yizhangyichi-api","version":"4bc2daf0f595725d8b20"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"env":"prod","run":"yizhangyichi-api","version":"4bc2daf0f595725d8b20"}},"spec":{"containers":[{"env":[{"name":"APP","value":"yizhangyichi"},{"name":"PORT","value":"3000"},{"name":"DB_DIALECT","value":"mysql"},{"name":"DB_HOST","value":"localhost"},{"name":"DB_PORT","value":"3307"},{"name":"DB_NAME","value":"yizhangyichi"},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"cloudsql-db-credentials"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"cloudsql-db-credentials"}}}],"image":"gcr.io/yizhangyichi-20180401/yizhangyichi-api:4bc2daf0f595725d8b20","imagePullPolicy":"IfNotPresent","name":"yizhangyichi-api","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"command":["/cloud_sql_proxy","-instances=yizhangyichi-20180401:us-central1:yizhangyichi=tcp:3307","-credential_file=/secrets/cloudsql/credentials.json"],"image":"gcr.io/cloudsql-docker/gce-proxy:1.11","imagePullPolicy":"IfNotPresent","name":"cloudsql-proxy","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/secrets/cloudsql","name":"cloudsql-instance-credentials","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"cloudsql-instance-credentials","secret":{"defaultMode":420,"secretName":"cloudsql-instance-credentials"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-05-07T09:08:41Z","lastUpdateTime":"2018-05-07T09:08:41Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2018-05-07T09:08:41Z
  generation: 3
  labels:
    env: prod
    run: yizhangyichi-api
    version: 4bc2daf0f595725d8b20
  name: yizhangyichi-api
  namespace: default
  resourceVersion: "848276"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/yizhangyichi-api
  uid: 3c696ef9-51d6-11e8-9a8b-42010af0022e
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
      run: yizhangyichi-api
      version: 4bc2daf0f595725d8b20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: prod
        run: yizhangyichi-api
        version: 4bc2daf0f595725d8b20
    spec:
      containers:
      - env:
        - name: APP
          value: yizhangyichi
        - name: PORT
          value: "3000"
        - name: DB_DIALECT
          value: mysql
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "3307"
        - name: DB_NAME
          value: yizhangyichi
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        image: gcr.io/yizhangyichi-20180401/yizhangyichi-api:4bc2daf0f595725d8b20
        imagePullPolicy: IfNotPresent
        name: yizhangyichi-api
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=yizhangyichi-20180401:us-central1:yizhangyichi=tcp:3307
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-07T09:08:41Z
    lastUpdateTime: 2018-05-07T09:08:41Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
