apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-05-07T09:08:41Z
  generation: 1
  labels:
    run: yizhangyichi-api
  name: yizhangyichi-api
  namespace: default
  resourceVersion: "205589"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/yizhangyichi-api
  uid: 3c696ef9-51d6-11e8-9a8b-42010af0022e
spec:
  replicas: 1
  selector:
    matchLabels:
      run: yizhangyichi-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: yizhangyichi-api
    spec:
      containers:
        - name: yizhangyichi-api
          image: gcr.io/yizhangyichi-20180401/yizhangyichi-api:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: APP
              value: yizhangyichi
            - name: PORT
              value: '3000'
            - name: DB_DIALECT
              value: mysql
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: '3307'
            - name: DB_NAME
              value: yizhangyichi
            # [START cloudsql_secrets]
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [START cloudsql_secrets]
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                      "-instances=yizhangyichi-20180401:us-central1:yizhangyichi=tcp:3307",
                      "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-07T09:08:41Z
    lastUpdateTime: 2018-05-07T09:08:41Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
