-- MySQL Script generated by MySQL Workbench
-- Fri May  4 07:09:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yizhangyichi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yizhangyichi` ;

-- -----------------------------------------------------
-- Schema yizhangyichi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yizhangyichi` DEFAULT CHARACTER SET utf8 ;
USE `yizhangyichi` ;

-- -----------------------------------------------------
-- Table `yizhangyichi`.`Todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yizhangyichi`.`Todo` ;

CREATE TABLE IF NOT EXISTS `yizhangyichi`.`Todo` (
  `id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NULL COMMENT '0: created\n1: finished\n2: snoozed',
  `type` INT NULL COMMENT '0 normal\n1 timer todo\n2 recur todo',
  `todo_type` VARCHAR(45) NOT NULL DEFAULT 'chi' COMMENT 'zhang\nchi',
  PRIMARY KEY (`id`, `todo_type`),
  INDEX `create` (`created_time` ASC),
  INDEX `update` (`updated_time` ASC),
  INDEX `status` (`status` ASC))
ENGINE = InnoDB PARTITION BY LIST COLUMNS(todo_type) PARTITIONS 2( PARTITION part0 VALUES IN ('zhang'),  PARTITION part1 VALUES IN ('chi')) ;


-- -----------------------------------------------------
-- Table `yizhangyichi`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yizhangyichi`.`Project` ;

CREATE TABLE IF NOT EXISTS `yizhangyichi`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `created_time` (`created_time` ASC),
  INDEX `updated_time` (`updated_time` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yizhangyichi`.`ProjectTodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yizhangyichi`.`ProjectTodo` ;

CREATE TABLE IF NOT EXISTS `yizhangyichi`.`ProjectTodo` (
  `todo_id` INT NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`todo_id`, `project_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
